image:
  tag: "uat-cbdc5a8e"
service:
  namespace: wil-uat
ingress:
  host: uat.wil.phraya.net
extraEnv:
  NEXT_PUBLIC_API_URL: "https://uat.wil.phraya.net/api/wil-service"
  COMMIT_ID: "cbdc5a8e"
  NODE_ENV: production
extraEnvSecrets: {}
