image:
  tag: "uat-25ea022d"
service:
  namespace: wil-uat
  replicas: 2
extraEnv:
  COMMIT_ID: "25ea022d"
  NODE_ENV: production
  REDIS_URL: "redis.wil-uat.svc.cluster.local:6379"
  SMTP_HOST: "mail.spacemail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "true"
  SMTP_USER: "wil@phraya.net"
  FROM_EMAIL: "wil@phraya.net"
  EMAIL_RATE_LIMIT: "19"
  EMAIL_RATE_DURATION: "3600000"
extraEnvSecrets:
  REDIS_PASSWORD:
    secretName: wil-service-mailer-secrets
    key: REDIS_PASSWORD
  SMTP_PASS:
    secretName: wil-service-mailer-secrets
    key: SMTP_PASS
ingress:
  host: uat.wil.phraya.net
