image:
  repository: harbor.wil.phraya.net/wil/wil-service
  tag: "latest"
  pullSecrets: harbor-registry-secret

service:
  namespace: wil-dev
  port: 6700
  replicas: 1
  healthCheckPath: /health

ingress:
  host: ""
  path: /api/wil-service
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"

extraEnv:
  COMMIT_ID: ""
  NODE_ENV: development
  API_PORT: "6700"
  DB_HOST: ""
  DB_PORT: "5432"
  DB_NAME: "wil"