image:
  tag: "uat-3e05a6ea"
service:
  namespace: wil-uat
  replicas: 2
ingress:
  host: uat.wil.phraya.net
extraEnv:
  COMMIT_ID: "3e05a6ea"
  NODE_ENV: production
  DB_HOST: "postgresql.wil-uat.svc.cluster.local"

extraEnvSecrets:
  DB_USER:
    secretName: wil-service-secret
    key: DB_USER
  DB_PASSWORD:
    secretName: wil-service-secret
    key: DB_PASSWORD
  JWT_SECRET:
    secretName: wil-service-secret
    key: JWT_SECRET
