image:
  tag: "dev-8f355a55"
service:
  namespace: wil-dev
ingress:
  host: dev.wil.phraya.net
extraEnv:
  COMMIT_ID: "8f355a55"
  NODE_ENV: development
  DB_HOST: "postgresql.wil-dev.svc.cluster.local"
