image:
  tag: "dev-bf275f60"
service:
  namespace: wil-dev
ingress:
  host: dev.wil.phraya.net
extraEnv:
  COMMIT_ID: "bf275f60"
  NODE_ENV: development
  DB_HOST: "postgresql.wil-dev.svc.cluster.local"
