image:
  tag: "v1.0.0"
service:
  namespace: wil-prd
  replicas: 3
ingress:
  host: api.wil.phraya.net
extraEnv:
  COMMIT_ID: ""
  NODE_ENV: production
  DB_HOST: "postgresql.wil-prd.svc.cluster.local"

extraEnvSecrets:
  DB_USER:
    secretName: wil-service-secret
    key: DB_USER
  DB_PASSWORD:
    secretName: wil-service-secret
    key: DB_PASSWORD
  JWT_SECRET:
    secretName: wil-service-secret
    key: JWT_SECRET
