image:
  tag: "dev-f7e9826f"
service:
  namespace: wil-dev
ingress:
  host: dev.wil.phraya.net
extraEnv:
  COMMIT_ID: "f7e9826f"
  NODE_ENV: development
  DB_HOST: "postgresql.wil-dev.svc.cluster.local"
extraEnvSecrets:
  DB_USER:
    secretName: wil-service-secret
    key: DB_USER
  DB_PASSWORD:
    secretName: wil-service-secret
    key: DB_PASSWORD
  JWT_SECRET:
    secretName: wil-service-secret
    key: JWT_SECRET
