community:
  enabled: true

monitoringPasscodeSecretName: sonarqube-monitoring-passcode
monitoringPasscodeSecretKey: passcode

ingress:
  enabled: true
  hosts:
    - name: sonarqube.wil.phraya.net
      path: /
      pathType: Prefix
  tls:
    - secretName: sonarqube-tls
      hosts:
        - sonarqube.wil.phraya.net
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    cpu: "50m"
    memory: "256Mi"  # ← เพิ่ม
  limits:
    cpu: "1000m"
    memory: "2Gi"

postgresql:
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"  # ← เอา " ออก
    limits:
      cpu: "500m"
      memory: "512Mi"