apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-service-uat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jenesix/wil-gitops
    targetRevision: HEAD
    path: apps/wil-service
    helm:
      releaseName: wil-service-uat
      valueFiles:
        - values.yaml
        - values-uat.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wil-uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
