apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-service-dev        # ← ชัดขึ้น
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jenesix/wil-gitops   # ← เอา่ ออก
    targetRevision: HEAD
    path: apps/wil-service     # ← แก้จาก apps/wil
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wil-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true