apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: wil-uat
type: Opaque
stringData:
  REDIS_PASSWORD: "R3d!R3d!s@W1l#2024$uat"

# Replace the password above with a secure value before applying in UAT.
